### ISSUE TITLE
fix error and configuration on docker-compose.yml to run docker for the best capture for automation

### ISSUE THREAD

**Issue by zie225** [RamiKrispin/deploy-flex-actions#1]
Hi @RamiKrispin 

- I have some error like in this picture. So how i can fix it, i use windows like OS.

![image](https://user-images.githubusercontent.com/17972148/190246561-777347de-935d-43ce-b62d-5a0b1864fc51.png)

-  Also another problem you need to take attention about [docker-compose.yml](https://github.com/RamiKrispin/deploy-flex-actions/blob/main/docker-compose.yml). The best to run docker is the configuration of [docker-compose.yml.](https://github.com/RamiKrispin/deploy-flex-actions/blob/main/docker-compose.yml).  So you can explain how we can do the configuration of the docker-compose.yml or fix my problem in this picture below?
- because when i run the docker-compose file i have this problem: 

![image](https://user-images.githubusercontent.com/17972148/190250248-54209bf8-7201-4402-b349-40394f9e4e61.png)

If i use [docker-compose.yml ](https://github.com/RamiKrispin/deploy-flex-actions/blob/main/docker-compose.yml) for Docker container,I think I can have the best way for automation package download and more because when I running the docker with` docker run -d -p 8787:8787 rkrispin/flex_dash_env:dev.0.0.0.9000 `on my environment I didn't see all the package download then also I can't create the dashboard because any package is on my environment.

**Comment by RamiKrispin** [comment]
Hi @zie225,

it seems like you are missing the environment variables. I added a section to the tutorial about the settings of those variables, please check and try:
https://github.com/RamiKrispin/deploy-flex-actions#setting-environment-variables
